apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kqff7nq92-nodejs
  janus-idp.io/tekton: kqff7nq92-nodejs
  backstage.io/kubernetes-id: kqff7nq92-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqff7nq92-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
